### PR TITLE
first commit to support modules properly in dashboard

### PR DESCRIPTION
**Pull request by luceos**
- Added module support (added only for side menu so far)
- Reordered registration of configuration file, because: `if (config('laraflock.dashboard.routes'))` fails if no configuration file was published for the package.

Hope hear your opinion about the module part.

### CODE REVIEW

**Comment by iolson** [comment]
Going to take a look at this, if you have a demo that would be great, otherwise I'll get it setup locally to test.

**Comment by luceos** [comment]
I do have a demo, but it's on local vagrant and a very poor connection. You can use `hyn-me/management-interface` the `dev-master` should work, be aware it includes `multi-tenant` too ;p

**Comment by luceos** [comment]
I updated the code to match your dev-master. Waiting for tests to finish.

**Comment by luceos** [comment]
Any update on this?

**Pull request merged**
